# spring配置
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      # 数据库
      database: 0
      # 主机
      host: 127.0.0.1
      # 端口
      port: 6379
      # 密码
      password: 123456
      # 读超时
      timeout: 5s
      # 连接超时
      connect-timeout: 5s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

    # mybatis配置
    # mybatis:
    #     # 搜索指定包别名
    #     typeAliasesPackage: com.honghao.fleet
    #     typeEnumsPackage: com.honghao.fleet.enums
    #     # 配置mapper的扫描，找到所有的mapper.xml映射文件
    #     mapperLocations: classpath:mapper/**/*.xml

    #pageSize可以为0，表示查全部
    # pagehelper:
    #   pageSizeZero: true

# #打印sql
# logging:
#   level:
#     com.honghao.fleet.mapper: debug
#     com.honghao.fleet.manager.mapper: debug
