spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: demo-test
          uri: lb://demo-test
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
