spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: demo-test
          uri: lb://demo-test
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

        - id: xigua-user
          uri: lb://xigua-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
