# Tomcat
server:
  port: 8082

# Spring
spring:
  application:
    # 应用名称
    name: xigua-user
  profiles:
    # 环境配置
    active: dev
  data:
    redis:
      # 数据库
      database: 0
      # 主机
      host: 127.0.0.1
      # 端口
      port: 6379
      # 密码
      password: 123456
      # 读超时
      timeout: 5s
      # 连接超时
      connect-timeout: 5s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xigua?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: xigua
      config:
        namespace: xigua
        # 配置文件格式
        file-extension: yaml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

dubbo:
  scan:
    base-packages: com.xigua
  protocol:
    name: dubbo
    port: 20882
  registry:
    check: false
    # 注册中心nacos
    address: nacos://127.0.0.1:8848
    # 指定nacos namespace命名空间
    parameters:
      namespace: xigua
  consumer:
    check: false
    # 重试为0
    retries: 0
    # 超时5秒
    timeout: 5000
    # 自定义过滤器（用来隐式传当前用户信息）
  #    filter: userContextFilter
  provider:
    check: false
    # 重试为0
    retries: 0
    # 超时5秒
    timeout: 5000
    # 自定义过滤器（用来隐式传当前用户信息）
#    filter: userContextFilter

logging:
  level:
    # kafka客户端检测打印error
    org.apache.kafka.clients: error
    # 打印sql
    com.xigua.demo.mapper: debug


# swagger配置
springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    path: /user/swagger-ui.html
