spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: demo-test
          uri: lb://demo-test
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

        - id: xigua-client
          uri: lb://xigua-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1

        - id: xigua-center
          uri: lb://xigua-center
          predicates:
            - Path=/center/**
          filters:
            - StripPrefix=1


        - id: xigua-sso
          uri: lb://xigua-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1

springdoc:
  webjars:
    # 设置为空，不要前缀
    prefix:
  swagger-ui:
    urls:
      - name: demo-api
        url: /demo/v3/api-docs
      - name: client-api
        url: /client/v3/api-docs
      - name: center-api
        url: /center/v3/api-docs
      - name: sso-api
        url: /sso/v3/api-docs
