spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: demo-test
          uri: lb://demo-test
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

        - id: xigua-user
          uri: lb://xigua-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: xigua-client
          uri: lb://xigua-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1

        - id: xigua-center
          uri: lb://xigua-center
          predicates:
            - Path=/center/**
          filters:
            - StripPrefix=1

springdoc:
  webjars:
    # 设置为空，不要前缀
    prefix:
  swagger-ui:
    urls:
      - name: demo-api
        url: /demo/v3/api-docs
      - name: user-api
        url: /user/v3/api-docs
